server:
  port: 8777 # Configurar el puerto del servidor Zuul

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/ # URL del servidor Eureka

spring:
  application:
    name: gateway-server # Nombre de la aplicaci칩n Zuul
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/service/**

#zuul:
#  routes:
#    users-service: # Nombre del microservicio que ser치 roteado
#      path: /api/users/** # Ruta que Zuul interceptar치 y redirigir치
#      serviceId: crud # Nombre del servicio en Eureka